[tool.poetry]
name = "000-markmaker"
version = "0.1.0"
description = ""
authors = ["Caleb <calebcauthon@gmail.com>"]
readme = "README.md"
packages = [{include = "000_markmaker"}]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"
flask-cors = "^5.0.0"
yt-dlp = "^2024.10.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
