name: Build Docker Image

on:
  workflow_dispatch:
    paths:
      - 'modal_app/**'
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./modal_app
          file: ./modal_app/Dockerfile-deploy-render
          push: false
          load: true
          tags: goalty-modal:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 